# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/ios'

begin
  require 'bundler'
  Bundler.require
rescue LoadError
end

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'app'
  app.frameworks += %w(CoreLocation CoreBluetooth)

  app.development do
    app.provisioning_profile = '/Users/omoon/Dropbox/tap_axolcheckin15_dev.mobileprovision'
    app.codesign_certificate = 'iPhone Developer: Sotaro OMURA (7S4256H3QK)'
  end
end
